config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#top'

  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :users, only: [:show, :edit, :index, :update]

  get 'home/about', to: 'home#about', as: :about 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user

  validates :title, presence: true
  # validates :image, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_one_attached :profile_image

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50}

  def get_profile_image(width = nil, height = nil)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_up_path_for(resource)
    user_path(resource)  # 新規登録したユーザーの詳細ページへリダイレクト
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def new
    @book = Book.new
  end

  def create
    @user = current_user
    @book = Book.all
    @booknew = Book.new(book_params)
    @booknew.user_id = current_user.id
    if @booknew.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@booknew)
    else
      # flash[:alert] = "You have failed to create the book.Please check your input."
      render :index
    end

  end
  
  def index
    @book = Book.all
    @booknew = Book.new
    @user = current_user
  end 

  def show
    @book = Book.find(params[:id])
    @books = Book.all
    @booknew = Book.new
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
  
    # ユーザーが自分の本だけを編集できるようにする
    unless @book.user_id == current_user.id
      redirect_to books_path, alert: "You are not authorized to edit this book."
    end
  end
  

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book)
    else
      flash.now[:alert] = "error Book was not created successfully"
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

    # 投稿データのストロングパラメータ
    private

    def book_params
      params.require(:book).permit(:title, :image, :body)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :ensure_correct_user, only: [:edit, :update]
  
  def index
    @book = Book.all
    @booknew = Book.new
    @user = current_user
    @users = User.all
  end 

  def show
    @user = User.find(params[:id])
    @book = @user.books
    @books = @user.books
    @booknew = Book.new
   end
  
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
  
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'You have updated user successfully.'
    else
      # flash.now[:alert] = 'You have failed to update the user.Please check your input.'
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:email, :name, :password, :profile_image, :introduction)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/index.html.erb
<div class="container px-5 px-sm-0 py-3">
  <div class="row">
    <div class="col-md-3">

    <!-- ユーザープロフィール -->
    <!-- 投稿機能 -->
    <!-- 共通部分テンプレート _sidbar.html.erbへ -->
    <%= render 'users/sidbar', booknew: @booknew , user: @user %>

    <!-- ユーザーの投稿一覧 -->
      <div class="col-md-8 offset-md-1">
        <!-- タイトルを変更 -->
          <% if request.path.include?("/books/") && request.path != books_path %>
            <h2>Book Detail</h2>
          <% elsif request.path == users_path %>
            <h2>Users</h2>
          <% elsif request.path == books_path || request.path.match?(/^\/users\/\d+$/) %>
            <h2>Books</h2>
          <% end %>

        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <% if request.path == "/users" %>
                <th>image</th>
                <th>name</th>
              <% elsif request.path == books_path %>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
              <% elsif request.path.match?(/^\/users\/\d+$/) %>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
              <% end %>
            </tr>
          </thead>
          <tbody>
            <% if request.path == "/users" %>
              <% @users.each do |user| %>
                <tr>
                  <td>
                    <%= image_tag user.get_profile_image(80, 80) %>
                  </td>
                  <td><%= user.name %></td>
                  <td>
                    <%= link_to "Show", user_path(user) %>
                  </td>
                </tr>
              <% end %>
            <% elsif request.path == books_path %>
              <% @book.each do |book| %>
                <tr>
                  <td>
                    <%= link_to user_path(book.user) do %>
                      <%= image_tag book.user.get_profile_image(80, 80) %>
                    <% end %>
                  </td>
                  <td><%= link_to book.title, book_path(book.id) %></td>
                  <td><%= book.body %></td>
                </tr>
              <% end %>
            <% elsif request.path.include?("/books/") %>
              <!-- 個別の本の詳細表示 -->
              <tr>
                <td colspan="3">
                  <table>
                    <tr>
                      <td><strong>タイトル：</strong></td>
                      <td><%= @book.title %></td>
                    </tr>
                    <tr>
                      <td><strong>投稿ユーザー画像：</strong></td>
                      <td><%= image_tag @book.user.get_profile_image(80, 80) %></td>
                    </tr>
                    <tr>
                      <td><strong>ユーザーネーム：</strong></td>
                      <td><%= @book.user.name %></td>
                    </tr>
                    <% if @book.user == current_user %>
                      <tr>
                        <td colspan="2">
                          <%= link_to "編集", edit_book_path(@book), class: "btn btn-success" %>
                          <%= link_to "削除", book_path(@book), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger" %>
                        </td>
                      </tr>
                    <% end %>
                  </table>
                </td>
              </tr>
            <% elsif request.path == user_path(user) %> <!-- 参照しているユーザーの詳細ページ -->
              <tr>
                <td colspan="3">
                  <table>
                    <tr>
                      <td><strong>ユーザー画像：</strong></td>
                      <td><%= image_tag user.get_profile_image(80, 80) %></td>
                    </tr>
                    <tr>
                      <td><strong>ユーザーネーム：</strong></td>
                      <td><%= user.name %></td>
                    </tr>
                    <tr>
                      <td><strong>自己紹介：</strong></td>
                      <td><%= user.introduction %></td>
                    </tr>
                  </table>
                </td>
              </tr>
            <% end %>            
          </tbody>
        </table>
      </div>

    </div>
  </div>
</div>

<style>
  .custom-btn {
    background-color: white;
    color: gray;
    border: 1px solid gray;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: background-color 0.3s ease, color 0.3s ease;
  }
  .custom-icon {
    color: gray;
    transition: color 0.3s ease;
  }
  .custom-btn:hover {
    background-color: gray;
    color: white;
  }
  .custom-btn:hover .custom-icon {
    color: white;
  }
</style>

app/views/books/new.html.erb
<h1>画像投稿フォーム</h1>

<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book do |f| %>
  <h4>画像</h4>
  <%= f.file_field :image, accept: "image/*" %>
  <h4>タイトル名</h4>
  <%= f.text_field :title %>
  <h4>感想</h4>
  <%= f.text_area :body %>
  <%= f.submit '投稿' %>
<% end %>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0 py-3">
  <div class="row">
    <div class="col-md-3">

    <!-- ユーザープロフィール -->
    <!-- 投稿機能 -->
    <!-- 共通部分テンプレート _sidbar.html.erbへ -->
    <%= render 'users/sidbar', booknew: @booknew , user: @user %>

    <!-- ユーザーの投稿一覧 -->
      <div class="col-md-8 offset-md-1">
        <!-- タイトルを変更 -->
          <% if request.path.include?("/books/") && request.path != books_path %>
            <h2>Book detail</h2>
          <% elsif request.path == users_path %>
            <h2>Users</h2>
          <% elsif request.path == books_path || request.path.match?(/^\/users\/\d+$/) %>
            <h2>Books</h2>
          <% end %>

        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <% if request.path == "/users" %>
                <th>image</th>
                <th>name</th>
              <% elsif request.path == books_path %>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
              <% elsif request.path.match?(/^\/users\/\d+$/) %>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
              <% end %>
            </tr>
          </thead>
          <tbody>
            <% if request.path == "/users" %>
              <% @users.each do |user| %>
                <tr>
                  <td>
                    <%= image_tag user.get_profile_image(80, 80) %>
                  </td>
                  <td><%= user.name %></td>
                  <td>
                    <%= link_to "Show", user_path(user) %>
                  </td>
                </tr>
              <% end %>
            <% elsif request.path == books_path %>
              <% @books.each do |book| %>
                <tr>
                  <td>
                    <%= link_to user_path(book.user) do %>
                      <%= image_tag book.get_image, width: 80, height: 80 %>
                    <% end %>
                  </td>
                  <td><%= link_to book.title, book_path(book.id) %></td>
                  <td><%= book.body %></td>
                </tr>
              <% end %>
            <% elsif request.path.include?("/books/") %>
              <!-- 個別の本の詳細表示 -->
              <tr>
              <td colspan="3">
                <table style="width: 100%; text-align: center;">
                  <tr>
                    <!-- ユーザー情報（プロフィール画像と名前） -->
                    <td style="text-align: center; padding: 10px;">
                      <%= image_tag @book.user.get_profile_image(80, 80) %><br>
                      <%= link_to @book.user.name, user_path(@book.user), class: "user-link" %>
                    </td>                  
                    
                    <!-- 本のタイトル -->
                    <td style="padding: 10px;">
                      <%= link_to @book.title, book_path(@book) %>
                    </td>
                    
                    <!-- 本の紹介文 -->
                    <td style="padding: 10px;">
                      <%= @book.body %>
                    </td>
                    
                    <!-- 編集・削除リンク（自分の投稿のみ表示） -->
                    <% if @book.user == current_user %>
                      <td style="padding: 10px;" colspan="2">
                        <div style="display: flex; align-items: center; gap: 10px;">
                          <%= link_to "Edit", edit_book_path(@book), class: "btn btn-success" %>
                          <%= link_to "Destroy", book_path(@book), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger" %>
                        </div>
                      </td>
                    <% end %>
                  </tr>
                  </table>
              </td>
              </tr>
            <% elsif request.path == user_path(user) %> <!-- 参照しているユーザーの詳細ページ -->
              <tr>
                <td colspan="3">
                  <table>
                    <tr>
                      <td><strong>ユーザー画像：</strong></td>
                      <td><%= image_tag user.get_profile_image(80, 80) %></td>
                    </tr>
                    <tr>
                      <td><strong>ユーザーネーム：</strong></td>
                      <td><%= user.name %></td>
                    </tr>
                    <tr>
                      <td><strong>自己紹介：</strong></td>
                      <td><%= user.introduction %></td>
                    </tr>
                  </table>
                </td>
              </tr>
            <% end %>                       
          </tbody>
        </table>
      </div>

    </div>
  </div>
</div>

<style>
  .custom-btn {
    background-color: white;
    color: gray;
    border: 1px solid gray;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: background-color 0.3s ease, color 0.3s ease;
  }
  .custom-icon {
    color: gray;
    transition: color 0.3s ease;
  }
  .custom-btn:hover {
    background-color: gray;
    color: white;
  }
  .custom-btn:hover .custom-icon {
    color: white;
  }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/44f6061d41.js" crossorigin="anonymous"></script>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/">
        <span>Bookers</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" 
      aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown" style="display: flex; justify-content: flex-end;">
        <ul style="list-style: none; display: flex; gap: 15px; margin: 0; padding: 0;">
          <% if user_signed_in? %>
            <li>
              <%= link_to user_path(current_user.id), style: "color: white; text-decoration: none; display: flex; align-items: center;" do %>
                <i class="fa-solid fa-house" style="margin-right: 4px;"></i>
                Home
              <% end %>
            </li>
            <li>
              <%= link_to users_path, style: "color: white; text-decoration: none; display: flex; align-items: center;" do %>
                <i class="fa-solid fa-users" style="margin-right: 4px;"></i>
                Users
              <% end %>
            </li>
            <li>
              <%= link_to books_path, style: "color: white; text-decoration: none; display: flex; align-items: center;" do %>
                <i class="fa-solid fa-book-open" style="margin-right: 4px;"></i>
                Books
              <% end %>
            </li>
            <li style="display: flex; align-items: center;">
              <%= link_to destroy_user_session_path, method: :delete, style: "color: white; text-decoration: none; display: flex; align-items: center;" do %>
                <i class="fa-solid fa-right-from-bracket" style="margin-right: 4px;"></i>
                Log out
              <% end %>
            </li>
          <% else %>
            <li style="display: flex; align-items: center;">
              <%= link_to root_path, style: "color: white; text-decoration: none; display: flex; align-items: center;" do %>
                <i class="fa-solid fa-house" style="margin-right: 4px;"></i>
                Home
              <% end %>
            </li>
            <li style="display: flex; align-items: center;">
              <%= link_to about_path, style: "color: white; text-decoration: none; display: flex; align-items: center;" do %>
                <i class="fa-solid fa-link" style="margin-right: 4px;"></i>
                About
              <% end %>
            </li>
            <li style="display: flex; align-items: center;">
              <%= link_to new_user_registration_path, style: "color: white; text-decoration: none; display: flex; align-items: center;" do  %>
                <i class="fa-solid fa-user-plus" style="margin-right: 4px;"></i>
                Sign up
              <% end %>
            </li>
            <li style="display: flex; align-items: center;">
              <%= link_to new_user_session_path, style: "color: white; text-decoration: none; display: flex; align-items: center;" do %>
                <i class="fa-solid fa-right-to-bracket" style="margin-right: 4px;"></i>
                Log in
              <% end %>
            </li>
          <% end %>      
        </ul>
      </div>
    </div>
  </nav>
</header>

  <main>
  <% if flash.present? %>
    <div class="flash-messages">
      <% flash.each do |type, message| %>
        <% type_class = type.to_s == "alert" ? "error" : "success" %>
        <div class="flash flash-<%= type_class %>">
          <%= message %>
        </div>
      <% end %>
    </div>
  <% end %>

  <div class="container">
    <div class="row">
    </div>
  </div>
  <%= yield %>
</main>

  <footer>
    <div class="container mt-5">
      <div class="row">
       <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
       </div>
      </div>
    </div>
  </footer>
</body>
  
</html>

app/views/users/_sidbar.html.erb
<% if booknew.errors.any? %>
  <%= booknew.errors.count %>件のエラーが発生しました
  <ul>
    <% booknew.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<!-- ユーザープロフィール -->
<div>
  <h2>User info</h2>


  <%= image_tag user.get_profile_image(100, 100) %>
  <table class="table">
    <tbody>
      <tr>
        <th>name</th>
        <th class="bold-text"><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th class="bold-text"><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>

  <div class="mt-3">
      <%= link_to edit_user_path(user), 
          class: "btn btn-outline-secondary px-4 py-2 custom-btn", 
          style: "width: 290px; height: 40px" do %>
        <i class="fa-solid fa-user-gear custom-icon"></i>
      <% end %>
  </div>

</div>

      
<!-- 投稿機能 -->

  <div class="mt-2"> 
    <h2>New book</h2>
  </div>
  
  <%= form_with model: booknew, url: books_path, method: :post do |f| %>
    <div class="mb-3">
      <label for="book_title" class="form-label">Title</label>
      <%= f.text_field :title, class: "form-control", id: "book_title" %>
    </div>
    <div class="mb-3">
      <label for="book_body" class="form-label">Opinion</label>
      <%= f.text_area :body, class: "form-control", id: "book_body" %>
    </div>
    <%= f.submit 'Create Book', class: "btn btn-success" %>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0 py-3">
  <div class="row">
    <div class="col-md-3">

    <!-- ユーザープロフィール -->
    <!-- 投稿機能 -->
    <!-- 共通部分テンプレート _sidbar.html.erbへ -->
    <%= render 'users/sidbar', booknew: @booknew , user: @user %>

    <!-- ユーザーの投稿一覧 -->
      <div class="col-md-8 offset-md-1">
        <!-- タイトルを変更 -->
          <% if request.path.include?("/books/") && request.path != books_path %>
            <h2>Book Detail</h2>
          <% elsif request.path == users_path %>
            <h2>Users</h2>
          <% elsif request.path == books_path || request.path.match?(/^\/users\/\d+$/) %>
            <h2>Books</h2>
          <% end %>
      
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <% if request.path == "/users" %>
                <th>image</th>
                <th>name</th>
              <% elsif request.path == books_path %>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
              <% elsif request.path.match?(/^\/users\/\d+$/) %>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
              <% end %>
            </tr>
          </thead>
          <tbody>
            <% if request.path == "/users" %>
              <% @users.each do |user| %>
                <tr>
                  <td>
                    <%= image_tag user.get_profile_image(80, 80) %>
                  </td>
                  <td><%= user.name %></td>
                  <td>
                    <%= link_to "Show", user_path(user) %>
                  </td>
                </tr>
              <% end %>
            <% elsif request.path == books_path %>
              <% @books.each do |book| %>
                <tr>
                  <td>
                    <%= link_to user_path(book.user) do %>
                      <%= image_tag book.user.get_profile_image(80, 80) %>
                    <% end %>
                  </td>
                  <td><%= link_to book.title, book_path(book.id) %></td>
                  <td><%= book.body %></td>
                </tr>
              <% end %>
            <% elsif request.path.include?("/books/") %>
              <!-- 個別の本の詳細表示 -->
              <tr>
                <td colspan="3">
                  <table>
                    <tr>
                      <td><strong>タイトル：</strong></td>
                      <td><%= @book.title %></td>
                    </tr>
                    <tr>
                      <td><strong>投稿ユーザー画像：</strong></td>
                      <td><%= image_tag @book.user.get_profile_image(80, 80) %></td>
                    </tr>
                    <tr>
                      <td><strong>ユーザーネーム：</strong></td>
                      <td><%= @book.user.name %></td>
                    </tr>
                    <% if @book.user == current_user %>
                      <tr>
                        <td colspan="2">
                          <%= link_to "編集", edit_book_path(@book), class: "btn btn-success" %>
                          <%= link_to "削除", book_path(@book), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger" %>
                        </td>
                      </tr>
                    <% end %>
                  </table>
                </td>
              </tr>
              <% elsif request.path == user_path(@user) %> <!-- 参照しているユーザーの詳細ページ -->
              <% @books.each do |book| %>
                <tr>
                  <td>
                    <%= link_to user_path(book.user) do %>
                      <%= image_tag book.user.get_profile_image(80, 80) %>
                    <% end %>
                  </td>
                  <td><%= link_to book.title, book_path(book.id) %></td>
                  <td><%= book.body %></td>
                </tr>
              <% end %>
            <% end %>  
          </tbody>
        </table>
      </div>

    </div>
  </div>
</div>

<style>
  .custom-btn {
    background-color: white;
    color: gray;
    border: 1px solid gray;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: background-color 0.3s ease, color 0.3s ease;
  }
  .custom-icon {
    color: gray;
    transition: color 0.3s ease;
  }
  .custom-btn:hover {
    background-color: gray;
    color: white;
  }
  .custom-btn:hover .custom-icon {
    color: white;
  }
</style>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0 py-3">
  <div class="row">
    <div class="col-md-3">

    <!-- ユーザープロフィール -->
    <!-- 投稿機能 -->
    <!-- 共通部分テンプレート _sidbar.html.erbへ -->
    <%= render 'users/sidbar', booknew: @booknew , user: @user %>

    <!-- ユーザーの投稿一覧 -->
      <div class="col-md-8 offset-md-1">
        <!-- タイトルを変更 -->
          <% if request.path.include?("/books/") && request.path != books_path %>
            <h2>Book Detail</h2>
          <% elsif request.path == users_path %>
            <h2>Users</h2>
          <% elsif request.path == books_path || request.path.match?(/^\/users\/\d+$/) %>
            <h2>Books</h2>
          <% end %>

        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <% if request.path == "/users" %>
                <th>image</th>
                <th>name</th>
              <% elsif request.path == books_path %>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
              <% elsif request.path.match?(/^\/users\/\d+$/) %>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
              <% end %>
            </tr>
          </thead>
          <tbody>
            <% if request.path == "/users" %>
              <% @users.each do |user| %>
                <tr>
                  <td>
                    <%= image_tag user.get_profile_image(80, 80) %>
                  </td>
                  <td><%= user.name %></td>
                  <td>
                    <%= link_to "Show", user_path(user) %>
                  </td>
                </tr>
              <% end %>
            <% elsif request.path == books_path %>
              <% @books.each do |book| %>
                <tr>
                  <td>
                    <%= link_to user_path(book.user) do %>
                      <%= image_tag book.user.get_profile_image(80, 80) %>
                    <% end %>
                  </td>
                  <td><%= link_to book.title, book_path(book.id) %></td>
                  <td><%= book.body %></td>
                </tr>
              <% end %>
            <% elsif request.path.include?("/books/") %>
              <!-- 個別の本の詳細表示 -->
              <tr>
                <td colspan="3">
                  <table>
                    <tr>
                      <td><strong>タイトル：</strong></td>
                      <td><%= @book.title %></td>
                    </tr>
                    <tr>
                      <td><strong>投稿ユーザー画像：</strong></td>
                      <td><%= image_tag @book.user.get_profile_image(80, 80) %></td>
                    </tr>
                    <tr>
                      <td><strong>ユーザーネーム：</strong></td>
                      <td><%= @book.user.name %></td>
                    </tr>
                    <% if @book.user == current_user %>
                      <tr>
                        <td colspan="2">
                          <%= link_to "編集", edit_book_path(@book), class: "btn btn-success" %>
                          <%= link_to "削除", book_path(@book), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger" %>
                        </td>
                      </tr>
                    <% end %>
                  </table>
                </td>
              </tr>
            <% elsif request.path == user_path(@user) %> <!-- 参照しているユーザーの詳細ページ -->
              <% @books.each do |book| %>
                <tr>
                  <td>
                    <%= link_to user_path(book.user) do %>
                      <%= image_tag book.user.get_profile_image(80, 80) %>
                    <% end %>
                  </td>
                  <td><%= link_to book.title, book_path(book.id) %></td>
                  <td><%= book.body %></td>
                </tr>
              <% end %>
            <% end %>            
          </tbody>
        </table>
      </div>

    </div>
  </div>
</div>

<style>
  .custom-btn {
    background-color: white;
    color: gray;
    border: 1px solid gray;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: background-color 0.3s ease, color 0.3s ease;
  }
  .custom-icon {
    color: gray;
    transition: color 0.3s ease;
  }
  .custom-btn:hover {
    background-color: gray;
    color: white;
  }
  .custom-btn:hover .custom-icon {
    color: white;
  }
</style>